/**
 * Questionnaire API - Handles submission to Supabase
 * This file should be loaded AFTER supabase-client.js
 */

const QuestionnaireAPI = {
    /**
     * Submit questionnaire answers to Supabase
     * @param {Object} answers - User's answers to questions
     * @param {string} userEmail - User's email (optional fallback)
     * @returns {Promise} Submission result with analysis data
     */
    async submit(answers, userEmail = null, userPlan = null) {
        try {
            console.log('📝 Submitting questionnaire to Worker API...');

            // Get current authenticated user
            const { data: { user }, error: authError } = await supabaseClient.auth.getUser();
            const token = (await supabaseClient.auth.getSession()).data.session?.access_token;

            if (authError || !user || !token) {
                console.error('❌ User not authenticated');
                throw new Error('Vous devez être connecté pour soumettre le questionnaire');
            }

            console.log('✅ User authenticated:', user.email);
            console.log('📋 User plan:', userPlan || 'auto-detect');

            // Fetch from Backend Worker
            const response = await fetch('https://ai-ikigai.ai-ikigai.workers.dev/api/questionnaire/submit', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({
                    answers,
                    email: user.email,
                    user_plan: userPlan // Pass detected plan if available
                })
            });

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(errorData.error || 'Erreur lors de l\'analyse');
            }

            const result = await response.json();
            console.log('✅ Analysis generated by worker:', result);

            return {
                success: true,
                analysisId: result.questionnaireId,
                questionnaireId: result.questionnaireId,
                analysis: result.analysis
            };

        } catch (error) {
            console.error('❌ Questionnaire submission error:', error);
            return {
                success: false,
                error: error.message
            };
        }
    },

    /**
     * Upload CV file to Supabase Storage
     * @param {File} file - CV file to upload
     * @returns {Promise} Upload result
     */
    async uploadCV(file) {
        try {
            console.log('📄 Uploading CV...');

            const { data: { user } } = await supabaseClient.auth.getUser();
            if (!user) throw new Error('User not authenticated');

            // Generate unique filename
            const fileExt = file.name.split('.').pop();
            const fileName = `${user.id}/${Date.now()}.${fileExt}`;

            // Upload to Supabase Storage
            const { data, error } = await supabaseClient.storage
                .from('cvs')
                .upload(fileName, file);

            if (error) throw error;

            console.log('✅ CV uploaded:', data.path);

            // Update user profile with CV path
            await supabaseClient
                .from('profiles')
                .update({ cv_path: data.path })
                .eq('id', user.id);

            return {
                success: true,
                cvPath: data.path,
                cvData: { path: data.path }
            };

        } catch (error) {
            console.error('❌ CV upload error:', error);
            return {
                success: false,
                error: error.message
            };
        }
    }
};

// Make available globally
window.QuestionnaireAPI = QuestionnaireAPI;

console.log('✅ QuestionnaireAPI loaded');
